### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:355:21

### ISSUE THREAD

**Issue by panmau** [Pitasi/dyn-wallpaper#11]
I had this script working for over a month now without having any problems. Now suddenly I get the following output:
```
$ dyn-wallpaper-linux "Bern" "/home/mau/Pictures/Wallpapers/Mojave" 
16 images found in /home/mau/Pictures/Wallpapers/Mojave
Output file: "/tmp/dyn_wallpaper.jpg"
Selected city: Bern
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:355:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
And the output with Backtrace:
```
$ RUST_BACKTRACE=1 dyn-wallpaper-linux "Bern" "/home/mau/Pictures/Wallpapers/Mojave"
16 images found in /home/mau/Pictures/Wallpapers/Mojave
Output file: "/tmp/dyn_wallpaper.jpg"
Selected city: Bern
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:355:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::panicking::panic
             at libcore/panicking.rs:52
   9: dyn_wallpaper::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start
```
I also tried something like this and got the same error:
`dyn-wallpaper-linux "Bern" "/home/mau/Pictures/Wallpapers/Mojave" "feh --no-fehbg --auto-reload --bg-scale {path}"`

I didn't make changes to my system recently so I have no clue what the problem might be.
I use an up to date Manjaro Linux with i3wm so setting an image directly with feh works well.

I hope you can help me troubleshooting this issue, as I loved this background!

**Comment by panmau** [comment]
Since yesterday morning it's working well again. I have no idea what changed that this issue popped up.
I'm closing this for now.

**Comment by panmau** [comment]
Somehow this issue appeared again now. I'm not sure why and how to actually resolve it for good.

**Comment by Pitasi** [comment]
hi, sorry to hear this problem happened again

what you're thinking of a recent package update? did you recently rebuilt the dyn-wallpaper binary?

**Comment by panmona** [comment]
No, I didn't change the binary since I started using this.

I was thinking that some Arch Linux package I updated recently interferes here but nothing looks suspicious from my update log (`grep -i installed /var/log/pacman.log`).

A restart seems to have fixed it again though. Not sure what is happening here.
