### ISSUE TITLE
Syntax Error 

### ISSUE THREAD

**Issue by lestercolton** [Pitasi/dyn-wallpaper#4]
Coding really is beyond me but I managed to follow all the steps and installed all the requirements.txt stuff. Now I get:

File "/Users/xxxxxxx/Downloads/dyn-wallpaper-master/set_wallpaper.py", line 145
    args.temp
SyntaxError: only named arguments may follow *expression

I'm not sure why that is, I did all the things according to your specification so far.

**Comment by Pitasi** [comment]
Hi, are you using Windows 10?
What version of python are you using?

Cheers

**Comment by Pitasi** [comment]
I'm not sure how you are running the script, but please double-check to be using Python 3 - the latest version is Python 3.7.1 and can be downloaded from https://www.python.org/downloads/.

I think you probably are running Python 2, an older and no longer supported version of Python :)

**Comment by lestercolton** [comment]
I am on a Hackintosh High Sierra and so I can’t just “upgrade” as you may understand.  I thank you and look forward to your work as it just looks magnificent. I’ll be using it on my windows 10!

Have a great day.

On 11 Nov 2018, at 13:26, Antonio Pitasi <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, I misread the file path and thought you were on Windows.

Mac OS is not supported yet, but it should be possible, I'll open another issue as a note for myself to work on it as soon as possible.

I'll keep you informed :)

**Comment by lestercolton** [comment]
Hello Antonio,

Thank you so much for the email!

Unfortunately I tested it and it tells me “cannot execute binary file”

I’ll attach a screenshot so you better understand what’s going on perhaps.

[image1.jpeg]

On 30 Dec 2018, at 13:25, Antonio Pitasi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @lestercolton<https://github.com/lestercolton>, it's been a while but I finally added support for OSX, while I rewrote the entire program in another language.

I didn't have the chance to test it on OSX so I don't really know if it's working or not, if you're still interested please download the program from https://github.com/Pitasi/dyn-wallpaper/releases/download/v0.1.0/dyn-wallpaper-osx.
Then open a terminal in the same folder of the downloaded file and run:

./dyn-wallpaper "Rome" "/folder/containing/images/"


(of course you can change Rome to your nearest city)

let me know if you manage to use it :)
