### ISSUE TITLE
Showing Error while Using!

### ISSUE THREAD

**Issue by Bearbobs** [Pitasi/dyn-wallpaper#6]
sudo ./dyn-wallpaper-linux "Mumbai" "/home/anuj/Images/Wallpapers"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:355:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by Pitasi** [comment]
Hi, it's been a while since I last used this.

Is there any particular reason for running it using sudo? Also, what Linux distribution and Desktop Environment are you using?

cheers

**Comment by Bearbobs** [comment]
Hey,
I am using Manjaro with deepin DE.
It was demanding admin privledges for executing.

Best Regards,

**Comment by Pitasi** [comment]
Mmm it shouldn't need admin privileges to change background.

I re-read my README and I think I missed a section where I explain how to use it for other DEs (i.e. gnome or deepin).

Can you please try to execute:
```
./dyn-wallpaper-linux Mumbai /home/anuj/Images/Wallpapers -c "gsettings set com.deepin.wrap.gnome.desktop.background picture-uri {path}"
```

Also, be sure to have the pictures inside `/home/anuj/Images/Wallpapers`.

if it's still not working I'll install Deepin myself to try :D

**Comment by Bearbobs** [comment]
`anuj@anuj-pc  Downloads ./dyn-wallpaper-linux Mumbai /home/anuj/Pictures/wallpapers/mojave-background -c "gsettings set com.deepin.wrap.gnome.desktop.background picture-uri /home/anuj/Pictures/wallpapers/mojave-background"
error: Found argument '-c' which wasn't expected, or isn't valid in this context

USAGE:
    dyn-wallpaper-linux <city> <images> [command]

For more information try --help
 ✘ anuj@anuj-pc  Downloads  ./dyn-wallpaper-linux Mumbai /home/anuj/Pictures/wallpapers/mojave-background "gsettings set com.deepin.wrap.gnome.desktop.background picture-uri /home/anuj/Pictures/wallpapers/mojave-background" 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:355:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
 ✘ anuj@anuj-pc  Downloads  
`
Traceback for the above command.

**Comment by saksham816** [comment]
same problem
` ./dyn-wallpaper-linux  "Mumbai" "/home/saksham/Pictures/wallpapers/mojave-background" "gsettings\ set\ org.gnome.desktop.background\ picture-uri\ {path}"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:355:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.`
