### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by lutzke** [Pitasi/dyn-wallpaper#7]
Yes, I am aware that there was an issue like this already submitted.

No, the person who submitted the issue did **not** provide a solution before closing it.

`
$ ./dyn-wallpaper-linux "Denver" ~/Pictures/Wallpapers/dynamic_wallpaper/mojave_dynamic/`
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:355:21
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by Pitasi** [comment]
Hi there.
I tried downloading all the images from https://files.rb.gd/mojave_dynamic.zip and unzipped them into `~/Pictures/mojave`. It actually works for me:
```
$ ./dyn-wallpaper-linux "Denver" ~/Pictures/mojave/
16 images found in /home/antonio/Pictures/mojave/
Output file: "/tmp/dyn_wallpaper.jpg"
Selected city: Denver
Now: 2020-03-24 10:55:45.140390260 UTC
```

can you make sure you have the 16 images in `~/Pictures/Wallpapers/dynamic_wallpaper/mojave_dynamic/`?

cheers

**Comment by Pitasi** [comment]
I also realized that I did not mention in the README that dyn-wallpaper uses "feh" by default to change the wallpaper.
If you are using Gnome as your DE you should run instead:
```
./dyn-wallpaper-linux "Rome" ~/Pictures/mojave "gsettings set org.gnome.desktop.background picture-uri {path}"
```

you can customize the command being executed for changing the wallpaper like that.

**Comment by lutzke** [comment]
Okay, yes I am using GNOME... I will try that :)

**Comment by panmau** [comment]
If someone stumbles upon this I just wanted to add that the same error occurs if you don't delete the MACOSX folder.
