### ISSUE TITLE
[Windows 10] - wallpaper always set using UTC time

### ISSUE THREAD

**Issue by ava1ar** [Pitasi/dyn-wallpaper#9]
Hi, trying dyn-wallpaper on the Windows 10 laptop. Looks like changing city doesn't actually change anything and I am getting image for the UTC.
```
C:\Apps>dyn-wallpaper-win.exe "New York" D:\Pictures\Wallpapers\MojaveDynamic
16 images found in D:\Pictures\Wallpapers\MojaveDynamic
Output file: "C:\Users\ava1ar\AppData\Local\Temp\dyn_wallpaper.jpg"
Selected city: New York
Now: 2020-06-08 00:43:11.187027 UTC
```
```
C:\Apps>dyn-wallpaper-win.exe "Singapore" D:\Pictures\Wallpapers\MojaveDynamic
16 images found in D:\Pictures\Wallpapers\MojaveDynamic
Output file: "C:\Users\ava1ar\AppData\Local\Temp\dyn_wallpaper.jpg"
Selected city: Singapore
Now: 2020-06-08 00:43:37.949767700 UTC
```
For both cases I am getting same "darkest" image from the wallpaper set (which is first one), corresponds UTC time, but not local time as expected.

Using version 0.1.0 under Windows 10 version 2004 (May 2010 update). 

Any ideas?

**Comment by Pitasi** [comment]
Hi, sounds like Windows 10 changed something and dyn-wallpaper is now broken. I'll need to investigate.

**Comment by Pitasi** [comment]
I tried on a Windows 10 machine and it's working.
Are the images ordered correctly? This is what I have:
![image](https://user-images.githubusercontent.com/15048443/84528405-eea9a080-acdf-11ea-95f5-c29e6d5946e7.png)

Did you try to leave the program running for some time and see if the wallpaper was actually changing?
